#pragma once
// Auto-generated from kernel/test_ecc.cl. Do not edit manually.
static const char* TEST_ECC_KERNEL_SOURCE =
    "// CACHE_BUST: 744656\n"
    "// ============================================================================\n"
    "// TRON ECC Test Kernel\n"
    "// Standalone kernel for debugging GPU ECC correctness\n"
    "// Uses STANDARD modular arithmetic (no Montgomery form)\n"
    "// ============================================================================\n"
    "\n"
    "// secp256k1 curve parameters\n"
    "constant ulong SECP256K1_P[4] = {0xFFFFFFFEFFFFFC2FUL, 0xFFFFFFFFFFFFFFFFUL, 0xFFFFFFFFFFFFFFFFUL, 0xFFFFFFFFFFFFFFFFUL};\n"
    "constant ulong SECP256K1_N[4] = {0xBFD25E8CD0364141UL, 0xBAAEDCE6AF48A03BUL, 0xFFFFFFFFFFFFFFFEUL, 0xFFFFFFFFFFFFFFFFUL};\n"
    "constant ulong SECP256K1_GX[4] = {0x59F2815B16F81798UL, 0x029BFCDB2DCE28D9UL, 0x55A06295CE870B07UL, 0x79BE667EF9DCBBACUL};\n"
    "constant ulong SECP256K1_GY[4] = {0x9C47D08FFB10D4B8UL, 0xFD17B448A6855419UL, 0x5DA4FBFC0E1108A8UL, 0x483ADA7726A3C465UL};\n"
    "\n"
    "// 256-bit big integer (4 x 64-bit limbs)\n"
    "typedef struct {\n"
    "    ulong d[4];\n"
    "} uint256;\n"
    "\n"
    "// Jacobian point\n"
    "typedef struct {\n"
    "    uint256 x, y, z;\n"
    "} jacobian_point;\n"
    "\n"
    "// uint256 helpers\n"
    "int uint256_cmp(const uint256* a, const uint256* b) {\n"
    "    for (int i = 3; i >= 0; i--) {\n"
    "        if (a->d[i] > b->d[i]) return 1;\n"
    "        if (a->d[i] < b->d[i]) return -1;\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "bool uint256_is_zero(const uint256* a) {\n"
    "    return (a->d[0] | a->d[1] | a->d[2] | a->d[3]) == 0;\n"
    "}\n"
    "\n"
    "// Load 32 bytes big-endian into uint256 (little-endian limbs)\n"
    "// bytes[0] is MSB -> goes into d[3] high bytes\n"
    "// bytes[31] is LSB -> goes into d[0] low bytes\n"
    "void uint256_from_bytes(uint256* a, const uchar* bytes) {\n"
    "    a->d[0] = ((ulong)bytes[24] << 56) | ((ulong)bytes[25] << 48) | ((ulong)bytes[26] << 40) | ((ulong)bytes[27] << 32) |\n"
    "              ((ulong)bytes[28] << 24) | ((ulong)bytes[29] << 16) | ((ulong)bytes[30] << 8)  | ((ulong)bytes[31]);\n"
    "    a->d[1] = ((ulong)bytes[16] << 56) | ((ulong)bytes[17] << 48) | ((ulong)bytes[18] << 40) | ((ulong)bytes[19] << 32) |\n"
    "              ((ulong)bytes[20] << 24) | ((ulong)bytes[21] << 16) | ((ulong)bytes[22] << 8)  | ((ulong)bytes[23]);\n"
    "    a->d[2] = ((ulong)bytes[8]  << 56) | ((ulong)bytes[9]  << 48) | ((ulong)bytes[10] << 40) | ((ulong)bytes[11] << 32) |\n"
    "              ((ulong)bytes[12] << 24) | ((ulong)bytes[13] << 16) | ((ulong)bytes[14] << 8)  | ((ulong)bytes[15]);\n"
    "    a->d[3] = ((ulong)bytes[0]  << 56) | ((ulong)bytes[1]  << 48) | ((ulong)bytes[2]  << 40) | ((ulong)bytes[3]  << 32) |\n"
    "              ((ulong)bytes[4]  << 24) | ((ulong)bytes[5]  << 16) | ((ulong)bytes[6]  << 8)  | ((ulong)bytes[7]);\n"
    "}\n"
    "\n"
    "// Store uint256 (little-endian limbs) to 32 bytes big-endian\n"
    "// d[3] (high limb) -> bytes[0..7] (MSB first)\n"
    "// d[0] (low limb)  -> bytes[24..31] (LSB last)\n"
    "void uint256_to_bytes(uchar* bytes, const uint256* a) {\n"
    "    bytes[0]  = (uchar)(a->d[3] >> 56); bytes[1]  = (uchar)(a->d[3] >> 48); bytes[2]  = (uchar)(a->d[3] >> 40); bytes[3]  = (uchar)(a->d[3] >> 32);\n"
    "    bytes[4]  = (uchar)(a->d[3] >> 24); bytes[5]  = (uchar)(a->d[3] >> 16); bytes[6]  = (uchar)(a->d[3] >> 8);  bytes[7]  = (uchar)(a->d[3]);\n"
    "    bytes[8]  = (uchar)(a->d[2] >> 56); bytes[9]  = (uchar)(a->d[2] >> 48); bytes[10] = (uchar)(a->d[2] >> 40); bytes[11] = (uchar)(a->d[2] >> 32);\n"
    "    bytes[12] = (uchar)(a->d[2] >> 24); bytes[13] = (uchar)(a->d[2] >> 16); bytes[14] = (uchar)(a->d[2] >> 8);  bytes[15] = (uchar)(a->d[2]);\n"
    "    bytes[16] = (uchar)(a->d[1] >> 56); bytes[17] = (uchar)(a->d[1] >> 48); bytes[18] = (uchar)(a->d[1] >> 40); bytes[19] = (uchar)(a->d[1] >> 32);\n"
    "    bytes[20] = (uchar)(a->d[1] >> 24); bytes[21] = (uchar)(a->d[1] >> 16); bytes[22] = (uchar)(a->d[1] >> 8);  bytes[23] = (uchar)(a->d[1]);\n"
    "    bytes[24] = (uchar)(a->d[0] >> 56); bytes[25] = (uchar)(a->d[0] >> 48); bytes[26] = (uchar)(a->d[0] >> 40); bytes[27] = (uchar)(a->d[0] >> 32);\n"
    "    bytes[28] = (uchar)(a->d[0] >> 24); bytes[29] = (uchar)(a->d[0] >> 16); bytes[30] = (uchar)(a->d[0] >> 8);  bytes[31] = (uchar)(a->d[0]);\n"
    "}\n"
    "void uint256_to_global_bytes(__global uchar* bytes, const uint256* a) {\n"
    "    bytes[0]  = (uchar)(a->d[3] >> 56); bytes[1]  = (uchar)(a->d[3] >> 48); bytes[2]  = (uchar)(a->d[3] >> 40); bytes[3]  = (uchar)(a->d[3] >> 32);\n"
    "    bytes[4]  = (uchar)(a->d[3] >> 24); bytes[5]  = (uchar)(a->d[3] >> 16); bytes[6]  = (uchar)(a->d[3] >> 8);  bytes[7]  = (uchar)(a->d[3]);\n"
    "    bytes[8]  = (uchar)(a->d[2] >> 56); bytes[9]  = (uchar)(a->d[2] >> 48); bytes[10] = (uchar)(a->d[2] >> 40); bytes[11] = (uchar)(a->d[2] >> 32);\n"
    "    bytes[12] = (uchar)(a->d[2] >> 24); bytes[13] = (uchar)(a->d[2] >> 16); bytes[14] = (uchar)(a->d[2] >> 8);  bytes[15] = (uchar)(a->d[2]);\n"
    "    bytes[16] = (uchar)(a->d[1] >> 56); bytes[17] = (uchar)(a->d[1] >> 48); bytes[18] = (uchar)(a->d[1] >> 40); bytes[19] = (uchar)(a->d[1] >> 32);\n"
    "    bytes[20] = (uchar)(a->d[1] >> 24); bytes[21] = (uchar)(a->d[1] >> 16); bytes[22] = (uchar)(a->d[1] >> 8);  bytes[23] = (uchar)(a->d[1]);\n"
    "    bytes[24] = (uchar)(a->d[0] >> 56); bytes[25] = (uchar)(a->d[0] >> 48); bytes[26] = (uchar)(a->d[0] >> 40); bytes[27] = (uchar)(a->d[0] >> 32);\n"
    "    bytes[28] = (uchar)(a->d[0] >> 24); bytes[29] = (uchar)(a->d[0] >> 16); bytes[30] = (uchar)(a->d[0] >> 8);  bytes[31] = (uchar)(a->d[0]);\n"
    "}\n"
    "\n"
    "// Modular subtraction: result = (a - b) mod p\n"
    "void uint256_sub_mod(uint256* result, const uint256* a, const uint256* b, const uint256* p) {\n"
    "    (void)p;\n"
    "    uint aa[8], bb[8], r[8];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        aa[2 * i] = (uint)(a->d[i] & 0xFFFFFFFFUL);\n"
    "        aa[2 * i + 1] = (uint)(a->d[i] >> 32);\n"
    "        bb[2 * i] = (uint)(b->d[i] & 0xFFFFFFFFUL);\n"
    "        bb[2 * i + 1] = (uint)(b->d[i] >> 32);\n"
    "    }\n"
    "\n"
    "    ulong borrow = 0;\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong subtrahend = (ulong)bb[i] + borrow;\n"
    "        ulong val = (ulong)aa[i];\n"
    "        r[i] = (uint)(val - subtrahend);\n"
    "        borrow = (val < subtrahend) ? 1 : 0;\n"
    "    }\n"
    "\n"
    "    if (borrow) {\n"
    "        const uint pp[8] = {0xFFFFFC2FU, 0xFFFFFFFEU, 0xFFFFFFFFU, 0xFFFFFFFFU,\n"
    "                            0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU};\n"
    "        ulong carry = 0;\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong v = (ulong)r[i] + (ulong)pp[i] + carry;\n"
    "            r[i] = (uint)v;\n"
    "            carry = v >> 32;\n"
    "        }\n"
    "        // The carry from adding p is the discarded 2^256 word from\n"
    "        // (a - b + p) represented in eight 32-bit limbs; do not fold it.\n"
    "        (void)carry;\n"
    "    }\n"
    "\n"
    "    result->d[0] = ((ulong)r[1] << 32) | (ulong)r[0];\n"
    "    result->d[1] = ((ulong)r[3] << 32) | (ulong)r[2];\n"
    "    result->d[2] = ((ulong)r[5] << 32) | (ulong)r[4];\n"
    "    result->d[3] = ((ulong)r[7] << 32) | (ulong)r[6];\n"
    "}\n"
    "\n"
    "// Modular addition: result = (a + b) mod p\n"
    "void uint256_add_mod(uint256* result, const uint256* a, const uint256* b, const uint256* p) {\n"
    "    (void)p;\n"
    "    uint aa[8], bb[8], r[8];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        aa[2 * i] = (uint)(a->d[i] & 0xFFFFFFFFUL);\n"
    "        aa[2 * i + 1] = (uint)(a->d[i] >> 32);\n"
    "        bb[2 * i] = (uint)(b->d[i] & 0xFFFFFFFFUL);\n"
    "        bb[2 * i + 1] = (uint)(b->d[i] >> 32);\n"
    "    }\n"
    "\n"
    "    ulong carry = 0;\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong v = (ulong)aa[i] + (ulong)bb[i] + carry;\n"
    "        r[i] = (uint)v;\n"
    "        carry = v >> 32;\n"
    "    }\n"
    "\n"
    "    // Fold one possible 2^256 overflow: 2^256 ≡ 2^32 + 977.\n"
    "    if (carry) {\n"
    "        ulong v = (ulong)r[0] + 977UL;\n"
    "        r[0] = (uint)v;\n"
    "        carry = v >> 32;\n"
    "        v = (ulong)r[1] + 1UL + carry;\n"
    "        r[1] = (uint)v;\n"
    "        carry = v >> 32;\n"
    "        for (int i = 2; i < 8 && carry; i++) {\n"
    "            v = (ulong)r[i] + carry;\n"
    "            r[i] = (uint)v;\n"
    "            carry = v >> 32;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    const uint pp[8] = {0xFFFFFC2FU, 0xFFFFFFFEU, 0xFFFFFFFFU, 0xFFFFFFFFU,\n"
    "                        0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU};\n"
    "    for (int iter = 0; iter < 2; iter++) {\n"
    "        int cmp = 0;\n"
    "        for (int i = 7; i >= 0; i--) {\n"
    "            if (r[i] > pp[i]) { cmp = 1; break; }\n"
    "            if (r[i] < pp[i]) { cmp = -1; break; }\n"
    "        }\n"
    "        if (cmp < 0) break;\n"
    "        ulong borrow = 0;\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong subtrahend = (ulong)pp[i] + borrow;\n"
    "            ulong val = (ulong)r[i];\n"
    "            r[i] = (uint)(val - subtrahend);\n"
    "            borrow = (val < subtrahend) ? 1 : 0;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    result->d[0] = ((ulong)r[1] << 32) | (ulong)r[0];\n"
    "    result->d[1] = ((ulong)r[3] << 32) | (ulong)r[2];\n"
    "    result->d[2] = ((ulong)r[5] << 32) | (ulong)r[4];\n"
    "    result->d[3] = ((ulong)r[7] << 32) | (ulong)r[6];\n"
    "}\n"
    "\n"
    "// Right shift\n"
    "void uint256_rshift1(uint256* result, const uint256* a) {\n"
    "    for (int i = 0; i < 3; i++) {\n"
    "        result->d[i] = (a->d[i] >> 1) | (a->d[i + 1] << 63);\n"
    "    }\n"
    "    result->d[3] = a->d[3] >> 1;\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// Standard Modular Multiplication (Correct, non-Montgomery)\n"
    "// Uses secp256k1 special reduction: 2^256 ≡ c (mod p), c = 0x1000003D1\n"
    "// ============================================================================\n"
    "\n"
    "constant uint256 SECP256K1_C = {{0x00000001000003D1UL, 0x0UL, 0x0UL, 0x0UL}};\n"
    "\n"
    "// 256x256 -> 512 bit multiplication\n"
    "// Uses 32-bit schoolbook limbs so every intermediate product fits in ulong.\n"
    "// The previous 64-bit carry accumulation lost carry when adding lo + carry,\n"
    "// which broke point doubling for k >= 2.\n"
    "void uint256_mul_512(ulong* out_hi, uint256* out_lo, const uint256* a, const uint256* b) {\n"
    "    uint a32[8];\n"
    "    uint b32[8];\n"
    "    uint t[16];\n"
    "\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        a32[2 * i] = (uint)(a->d[i] & 0xFFFFFFFFUL);\n"
    "        a32[2 * i + 1] = (uint)(a->d[i] >> 32);\n"
    "        b32[2 * i] = (uint)(b->d[i] & 0xFFFFFFFFUL);\n"
    "        b32[2 * i + 1] = (uint)(b->d[i] >> 32);\n"
    "    }\n"
    "    for (int i = 0; i < 16; i++) t[i] = 0;\n"
    "\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong carry = 0;\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            ulong prod = (ulong)a32[i] * (ulong)b32[j] + (ulong)t[i + j] + carry;\n"
    "            t[i + j] = (uint)(prod & 0xFFFFFFFFUL);\n"
    "            carry = prod >> 32;\n"
    "        }\n"
    "\n"
    "        int k = i + 8;\n"
    "        while (carry != 0 && k < 16) {\n"
    "            ulong sum = (ulong)t[k] + carry;\n"
    "            t[k] = (uint)(sum & 0xFFFFFFFFUL);\n"
    "            carry = sum >> 32;\n"
    "            k++;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        out_lo->d[i] = ((ulong)t[2 * i + 1] << 32) | (ulong)t[2 * i];\n"
    "        out_hi[i] = ((ulong)t[2 * (i + 4) + 1] << 32) | (ulong)t[2 * (i + 4)];\n"
    "    }\n"
    "}\n"
    "\n"
    "// Multiply by c = 2^256 mod p = 2^32 + 2^9 + 2^8 + 2^7 + 2^6 + 2^4 + 1\n"
    "void uint256_mul_by_c(uint256* out, const uint256* in, const uint256* p) {\n"
    "    uint256 acc = *in;  // in * 1\n"
    "    uint256 shifted;\n"
    "    // in << 4 (2^4)\n"
    "    shifted.d[0] = in->d[0] << 4;\n"
    "    shifted.d[1] = (in->d[1] << 4) | (in->d[0] >> 60);\n"
    "    shifted.d[2] = (in->d[2] << 4) | (in->d[1] >> 60);\n"
    "    shifted.d[3] = (in->d[3] << 4) | (in->d[2] >> 60);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    // in << 6 (2^6)\n"
    "    shifted.d[0] = in->d[0] << 6;\n"
    "    shifted.d[1] = (in->d[1] << 6) | (in->d[0] >> 58);\n"
    "    shifted.d[2] = (in->d[2] << 6) | (in->d[1] >> 58);\n"
    "    shifted.d[3] = (in->d[3] << 6) | (in->d[2] >> 58);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    // in << 7 (2^7)\n"
    "    shifted.d[0] = in->d[0] << 7;\n"
    "    shifted.d[1] = (in->d[1] << 7) | (in->d[0] >> 57);\n"
    "    shifted.d[2] = (in->d[2] << 7) | (in->d[1] >> 57);\n"
    "    shifted.d[3] = (in->d[3] << 7) | (in->d[2] >> 57);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    // in << 8 (2^8)\n"
    "    shifted.d[0] = in->d[0] << 8;\n"
    "    shifted.d[1] = (in->d[1] << 8) | (in->d[0] >> 56);\n"
    "    shifted.d[2] = (in->d[2] << 8) | (in->d[1] >> 56);\n"
    "    shifted.d[3] = (in->d[3] << 8) | (in->d[2] >> 56);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    // in << 9 (2^9)\n"
    "    shifted.d[0] = in->d[0] << 9;\n"
    "    shifted.d[1] = (in->d[1] << 9) | (in->d[0] >> 55);\n"
    "    shifted.d[2] = (in->d[2] << 9) | (in->d[1] >> 55);\n"
    "    shifted.d[3] = (in->d[3] << 9) | (in->d[2] >> 55);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    // in << 32 (2^32)\n"
    "    shifted.d[0] = in->d[0] << 32;\n"
    "    shifted.d[1] = (in->d[1] << 32) | (in->d[0] >> 32);\n"
    "    shifted.d[2] = (in->d[2] << 32) | (in->d[1] >> 32);\n"
    "    shifted.d[3] = (in->d[3] << 32) | (in->d[2] >> 32);\n"
    "    uint256_add_mod(&acc, &acc, &shifted, p);\n"
    "    *out = acc;\n"
    "}\n"
    "\n"
    "// Standard modular multiplication: result = (a * b) mod p\n"
    "// 32-bit limb implementation with secp256k1 special reduction.\n"
    "// p = 2^256 - c, c = 2^32 + 977, so 2^256 ≡ c (mod p).\n"
    "void uint256_mul_mod(uint256* result, const uint256* a, const uint256* b, const uint256* p) {\n"
    "    (void)p;\n"
    "    uint aa[8], bb[8], prod[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        aa[2 * i] = (uint)(a->d[i] & 0xFFFFFFFFUL);\n"
    "        aa[2 * i + 1] = (uint)(a->d[i] >> 32);\n"
    "        bb[2 * i] = (uint)(b->d[i] & 0xFFFFFFFFUL);\n"
    "        bb[2 * i + 1] = (uint)(b->d[i] >> 32);\n"
    "    }\n"
    "    for (int i = 0; i < 16; i++) prod[i] = 0;\n"
    "\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong carry = 0;\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            ulong v = (ulong)prod[i + j] + (ulong)aa[i] * (ulong)bb[j] + carry;\n"
    "            prod[i + j] = (uint)v;\n"
    "            carry = v >> 32;\n"
    "        }\n"
    "        int k = i + 8;\n"
    "        while (carry && k < 16) {\n"
    "            ulong v = (ulong)prod[k] + carry;\n"
    "            prod[k] = (uint)v;\n"
    "            carry = v >> 32;\n"
    "            k++;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    // Fold high limbs with 2^256 == 2^32 + 977. Keep extra space for carries.\n"
    "    ulong acc[12];\n"
    "    for (int i = 0; i < 12; i++) acc[i] = 0;\n"
    "    for (int i = 0; i < 8; i++) acc[i] = prod[i];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        acc[i] += (ulong)prod[i + 8] * 977UL;\n"
    "        acc[i + 1] += (ulong)prod[i + 8];\n"
    "    }\n"
    "\n"
    "    // Propagate, then fold any limbs above 255 bits again. Two passes are enough\n"
    "    // for the bounded 512-bit product, but loop defensively.\n"
    "    for (int pass = 0; pass < 4; pass++) {\n"
    "        for (int i = 0; i < 11; i++) {\n"
    "            acc[i + 1] += acc[i] >> 32;\n"
    "            acc[i] &= 0xFFFFFFFFUL;\n"
    "        }\n"
    "        ulong hi0 = acc[8];\n"
    "        ulong hi1 = acc[9];\n"
    "        ulong hi2 = acc[10];\n"
    "        ulong hi3 = acc[11];\n"
    "        if ((hi0 | hi1 | hi2 | hi3) == 0) break;\n"
    "        acc[8] = acc[9] = acc[10] = acc[11] = 0;\n"
    "        ulong highs[4] = {hi0, hi1, hi2, hi3};\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            acc[i] += highs[i] * 977UL;\n"
    "            acc[i + 1] += highs[i];\n"
    "        }\n"
    "    }\n"
    "    for (int i = 0; i < 11; i++) {\n"
    "        acc[i + 1] += acc[i] >> 32;\n"
    "        acc[i] &= 0xFFFFFFFFUL;\n"
    "    }\n"
    "\n"
    "    uint r[8];\n"
    "    for (int i = 0; i < 8; i++) r[i] = (uint)acc[i];\n"
    "    const uint pp[8] = {0xFFFFFC2FU, 0xFFFFFFFEU, 0xFFFFFFFFU, 0xFFFFFFFFU,\n"
    "                        0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU};\n"
    "\n"
    "    // Final reduction. At most a few subtractions after folding.\n"
    "    for (int iter = 0; iter < 4; iter++) {\n"
    "        int cmp = 0;\n"
    "        for (int i = 7; i >= 0; i--) {\n"
    "            if (r[i] > pp[i]) { cmp = 1; break; }\n"
    "            if (r[i] < pp[i]) { cmp = -1; break; }\n"
    "        }\n"
    "        if (cmp < 0) break;\n"
    "        ulong borrow = 0;\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong subtrahend = (ulong)pp[i] + borrow;\n"
    "            ulong val = (ulong)r[i];\n"
    "            r[i] = (uint)(val - subtrahend);\n"
    "            borrow = (val < subtrahend) ? 1 : 0;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    result->d[0] = ((ulong)r[1] << 32) | (ulong)r[0];\n"
    "    result->d[1] = ((ulong)r[3] << 32) | (ulong)r[2];\n"
    "    result->d[2] = ((ulong)r[5] << 32) | (ulong)r[4];\n"
    "    result->d[3] = ((ulong)r[7] << 32) | (ulong)r[6];\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// Point operations using STANDARD modular arithmetic\n"
    "// ============================================================================\n"
    "\n"
    "// Point doubling: R = 2P in Jacobian coordinates\n"
    "// For secp256k1 (a=0):\n"
    "// S = 4*X*Y²\n"
    "// M = 3*X²\n"
    "// X' = M² - 2*S\n"
    "// Y' = M*(S - X') - 8*Y⁴\n"
    "// Z' = 2*Y*Z\n"
    "void point_double_v7(jacobian_point* r, const jacobian_point* p, const uint256* prime) {\n"
    "    // Make the function alias-safe: scalar multiplication calls\n"
    "    // point_double_v7(result, result, ...). Z' is computed after Y' is written,\n"
    "    // so reading directly from p would otherwise see the modified r->y.\n"
    "    jacobian_point in = *p;\n"
    "    p = &in;\n"
    "\n"
    "    uint256 s, m, temp1, temp2, y_sq, y_sq_sq;\n"
    "    \n"
    "    // Y²\n"
    "    uint256_mul_mod(&y_sq, &p->y, &p->y, prime);\n"
    "    // Y⁴\n"
    "    uint256_mul_mod(&y_sq_sq, &y_sq, &y_sq, prime);\n"
    "    \n"
    "    // S = 4*X*Y²\n"
    "    uint256_mul_mod(&temp1, &p->x, &y_sq, prime);  // X*Y²\n"
    "    uint256_add_mod(&s, &temp1, &temp1, prime);     // 2*X*Y²\n"
    "    uint256_add_mod(&s, &s, &temp1, prime);        // 3*X*Y²\n"
    "    uint256_add_mod(&s, &s, &temp1, prime);        // 4*X*Y²\n"
    "    \n"
    "    // M = 3*X² (a=0 for secp256k1)\n"
    "    uint256_mul_mod(&temp1, &p->x, &p->x, prime);  // X²\n"
    "    uint256_add_mod(&m, &temp1, &temp1, prime);     // 2*X²\n"
    "    uint256_add_mod(&m, &m, &temp1, prime);         // 3*X²\n"
    "    \n"
    "    // X' = M² - 2*S\n"
    "    uint256_mul_mod(&temp1, &m, &m, prime);         // M²\n"
    "    uint256_add_mod(&temp2, &s, &s, prime);         // 2*S\n"
    "    uint256_sub_mod(&r->x, &temp1, &temp2, prime);\n"
    "    \n"
    "    // Y' = M*(S - X') - 8*Y⁴\n"
    "    uint256_sub_mod(&temp1, &s, &r->x, prime);\n"
    "    uint256_mul_mod(&temp2, &m, &temp1, prime);\n"
    "    \n"
    "    // 8*Y⁴\n"
    "    uint256_add_mod(&temp1, &y_sq_sq, &y_sq_sq, prime);  // 2*Y⁴\n"
    "    uint256_add_mod(&temp1, &temp1, &y_sq_sq, prime);    // 3*Y⁴\n"
    "    uint256_add_mod(&temp1, &temp1, &y_sq_sq, prime);    // 4*Y⁴\n"
    "    uint256_add_mod(&temp1, &temp1, &temp1, prime);      // 8*Y⁴\n"
    "    \n"
    "    uint256_sub_mod(&r->y, &temp2, &temp1, prime);\n"
    "    \n"
    "    // Z' = 2*Y*Z\n"
    "    uint256_mul_mod(&temp1, &p->y, &p->z, prime);\n"
    "    uint256_add_mod(&r->z, &temp1, &temp1, prime);\n"
    "}\n"
    "\n"
    "// Point addition: R = P + Q\n"
    "void point_add_std(jacobian_point* r, const jacobian_point* p,\n"
    "                   const uint256* qx, const uint256* qy, const uint256* prime) {\n"
    "    uint256 z1_sq, z1_cu, u1, u2, s1, s2, h, h_sq, h_cu, r_val, temp1, temp2;\n"
    "    \n"
    "    // Z1², Z1³\n"
    "    uint256_mul_mod(&z1_sq, &p->z, &p->z, prime);\n"
    "    uint256_mul_mod(&z1_cu, &z1_sq, &p->z, prime);\n"
    "    \n"
    "    // U2 = X2 * Z1², S2 = Y2 * Z1³\n"
    "    uint256_mul_mod(&u2, qx, &z1_sq, prime);\n"
    "    uint256_mul_mod(&s2, qy, &z1_cu, prime);\n"
    "    \n"
    "    // U1 = X1, S1 = Y1\n"
    "    u1 = p->x;\n"
    "    s1 = p->y;\n"
    "    \n"
    "    // H = U2 - U1\n"
    "    uint256_sub_mod(&h, &u2, &u1, prime);\n"
    "    \n"
    "    // R = S2 - S1\n"
    "    uint256_sub_mod(&r_val, &s2, &s1, prime);\n"
    "    \n"
    "    // H², H³\n"
    "    uint256_mul_mod(&h_sq, &h, &h, prime);\n"
    "    uint256_mul_mod(&h_cu, &h_sq, &h, prime);\n"
    "    \n"
    "    // X3 = R² - H³ - 2*U1*H²\n"
    "    uint256_mul_mod(&temp1, &r_val, &r_val, prime);  // R²\n"
    "    uint256_sub_mod(&temp1, &temp1, &h_cu, prime);    // R² - H³\n"
    "    \n"
    "    uint256_mul_mod(&temp2, &u1, &h_sq, prime);       // U1*H²\n"
    "    uint256_add_mod(&temp2, &temp2, &temp2, prime);   // 2*U1*H²\n"
    "    uint256_sub_mod(&r->x, &temp1, &temp2, prime);    // R² - H³ - 2*U1*H²\n"
    "    \n"
    "    // Y3 = R*(U1*H² - X3) - S1*H³\n"
    "    uint256_mul_mod(&temp1, &u1, &h_sq, prime);       // U1*H²\n"
    "    uint256_sub_mod(&temp1, &temp1, &r->x, prime);    // U1*H² - X3\n"
    "    uint256_mul_mod(&temp2, &r_val, &temp1, prime);   // R*(U1*H² - X3)\n"
    "    \n"
    "    uint256_mul_mod(&temp1, &s1, &h_cu, prime);       // S1*H³\n"
    "    uint256_sub_mod(&r->y, &temp2, &temp1, prime);    // R*(U1*H² - X3) - S1*H³\n"
    "    \n"
    "    // Z3 = H * Z1\n"
    "    uint256_mul_mod(&r->z, &h, &p->z, prime);\n"
    "}\n"
    "\n"
    "// Jacobian to Affine\n"
    "void jacobian_to_affine_std(uint256* ax, uint256* ay, const jacobian_point* p, const uint256* prime) {\n"
    "    uint256 z_inv, z_inv_sq, z_inv_cu;\n"
    "    \n"
    "    // Z⁻¹ = Z^(p-2) mod p (Fermat's little theorem)\n"
    "    uint256 p_minus_2;\n"
    "    p_minus_2.d[0] = 0xFFFFFFFEFFFFFC2DUL;\n"
    "    p_minus_2.d[1] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    p_minus_2.d[2] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    p_minus_2.d[3] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    \n"
    "    // Modular exponentiation: z_inv = p->z ^ (p-2) mod p\n"
    "    uint256 base = p->z;\n"
    "    uint256 exp = p_minus_2;\n"
    "    uint256 result;\n"
    "    result.d[0] = 1; result.d[1] = 0; result.d[2] = 0; result.d[3] = 0;\n"
    "    \n"
    "    while (!uint256_is_zero(&exp)) {\n"
    "        if (exp.d[0] & 1) {\n"
    "            uint256_mul_mod(&result, &result, &base, prime);\n"
    "        }\n"
    "        uint256_mul_mod(&base, &base, &base, prime);\n"
    "        uint256_rshift1(&exp, &exp);\n"
    "    }\n"
    "    z_inv = result;\n"
    "    \n"
    "    // Z⁻² = (Z⁻¹)²\n"
    "    uint256_mul_mod(&z_inv_sq, &z_inv, &z_inv, prime);\n"
    "    \n"
    "    // Z⁻³ = Z⁻² * Z⁻¹\n"
    "    uint256_mul_mod(&z_inv_cu, &z_inv_sq, &z_inv, prime);\n"
    "    \n"
    "    // x = X * Z⁻²\n"
    "    uint256_mul_mod(ax, &p->x, &z_inv_sq, prime);\n"
    "    \n"
    "    // y = Y * Z⁻³\n"
    "    uint256_mul_mod(ay, &p->y, &z_inv_cu, prime);\n"
    "}\n"
    "\n"
    "// Scalar multiplication using double-and-add\n"
    "void scalar_multiply_base_std(jacobian_point* result, const uint256* k, const uint256* prime) {\n"
    "    // Initialize result to point at infinity\n"
    "    result->x = (uint256){{0, 0, 0, 0}};\n"
    "    result->y = (uint256){{0, 0, 0, 0}};\n"
    "    result->z = (uint256){{0, 0, 0, 0}};\n"
    "    \n"
    "    // Generator point G\n"
    "    uint256 gx, gy;\n"
    "    gx.d[0] = 0x59F2815B16F81798UL;\n"
    "    gx.d[1] = 0x029BFCDB2DCE28D9UL;\n"
    "    gx.d[2] = 0x55A06295CE870B07UL;\n"
    "    gx.d[3] = 0x79BE667EF9DCBBACUL;\n"
    "    \n"
    "    gy.d[0] = 0x9C47D08FFB10D4B8UL;\n"
    "    gy.d[1] = 0xFD17B448A6855419UL;\n"
    "    gy.d[2] = 0x5DA4FBFC0E1108A8UL;\n"
    "    gy.d[3] = 0x483ADA7726A3C465UL;\n"
    "    \n"
    "    // Find the highest set bit\n"
    "    int highest_bit = 255;\n"
    "    while (highest_bit >= 0) {\n"
    "        int limb = highest_bit / 64;\n"
    "        int bit_in_limb = highest_bit % 64;\n"
    "        if ((k->d[limb] >> bit_in_limb) & 1) break;\n"
    "        highest_bit--;\n"
    "    }\n"
    "    \n"
    "    if (highest_bit < 0) {\n"
    "        return;  // k = 0\n"
    "    }\n"
    "    \n"
    "    // Initialize result with G for the highest bit\n"
    "    result->x = gx;\n"
    "    result->y = gy;\n"
    "    result->z = (uint256){{1, 0, 0, 0}};\n"
    "    \n"
    "    // Process remaining bits\n"
    "    for (int i = highest_bit - 1; i >= 0; i--) {\n"
    "        point_double_v7(result, result, prime);\n"
    "        \n"
    "        int bit = (int)((k->d[i / 64] >> (i % 64)) & 1);\n"
    "        if (bit) {\n"
    "            point_add_std(result, result, &gx, &gy, prime);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// Generate public key from private key\n"
    "void generate_public_key_std(uchar* public_key, const uchar* private_key, const uint256* prime) {\n"
    "    uint256 k;\n"
    "    uint256_from_bytes(&k, private_key);\n"
    "    \n"
    "    jacobian_point result;\n"
    "    scalar_multiply_base_std(&result, &k, prime);\n"
    "    \n"
    "    uint256 ax, ay;\n"
    "    jacobian_to_affine_std(&ax, &ay, &result, prime);\n"
    "    \n"
    "    uint256_to_bytes(public_key, &ax);\n"
    "    uint256_to_bytes(public_key + 32, &ay);\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// Keccak-256\n"
    "// ============================================================================\n"
    "\n"
    "#define KECCAK_RATE 136\n"
    "#define KECCAK_STATE_SIZE 25\n"
    "\n"
    "ulong rol64(ulong x, int n) {\n"
    "    return (x << n) | (x >> (64 - n));\n"
    "}\n"
    "\n"
    "constant ulong KECCAK_RC[24] = {\n"
    "    0x0000000000000001UL, 0x0000000000008082UL, 0x800000000000808aUL,\n"
    "    0x8000000080008000UL, 0x000000000000808bUL, 0x0000000080000001UL,\n"
    "    0x8000000080008081UL, 0x8000000000008009UL, 0x000000000000008aUL,\n"
    "    0x0000000000000088UL, 0x0000000080008009UL, 0x000000008000000aUL,\n"
    "    0x000000008000808bUL, 0x800000000000008bUL, 0x8000000000008089UL,\n"
    "    0x8000000000008003UL, 0x8000000000008002UL, 0x8000000000000080UL,\n"
    "    0x000000000000800aUL, 0x800000008000000aUL, 0x8000000080008081UL,\n"
    "    0x8000000000008080UL, 0x0000000080000001UL, 0x8000000080008008UL\n"
    "};\n"
    "\n"
    "void keccak_f(ulong* state) {\n"
    "    ulong t[5];\n"
    "    ulong bc[5];\n"
    "    \n"
    "    for (int round = 0; round < 24; round++) {\n"
    "        // Theta\n"
    "        for (int i = 0; i < 5; i++) {\n"
    "            bc[i] = state[i] ^ state[i + 5] ^ state[i + 10] ^ state[i + 15] ^ state[i + 20];\n"
    "        }\n"
    "        for (int i = 0; i < 5; i++) {\n"
    "            t[i] = bc[(i + 4) % 5] ^ rol64(bc[(i + 1) % 5], 1);\n"
    "        }\n"
    "        for (int i = 0; i < 25; i++) {\n"
    "            state[i] ^= t[i % 5];\n"
    "        }\n"
    "        \n"
    "        // Rho and Pi\n"
    "        ulong last = state[1];\n"
    "        int piln[24] = {\n"
    "            10, 7, 11, 17, 18, 3, 5, 16, 8, 21, 24, 4,\n"
    "            15, 23, 19, 13, 12, 2, 20, 14, 22, 9, 6, 1\n"
    "        };\n"
    "        int rotc[24] = {\n"
    "            1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14,\n"
    "            27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44\n"
    "        };\n"
    "        for (int i = 0; i < 24; i++) {\n"
    "            ulong temp = state[piln[i]];\n"
    "            state[piln[i]] = rol64(last, rotc[i]);\n"
    "            last = temp;\n"
    "        }\n"
    "        \n"
    "        // Chi\n"
    "        for (int j = 0; j < 25; j += 5) {\n"
    "            for (int i = 0; i < 5; i++) {\n"
    "                t[i] = state[j + i];\n"
    "            }\n"
    "            for (int i = 0; i < 5; i++) {\n"
    "                state[j + i] ^= (~t[(i + 1) % 5]) & t[(i + 2) % 5];\n"
    "            }\n"
    "        }\n"
    "        \n"
    "        // Iota\n"
    "        state[0] ^= KECCAK_RC[round];\n"
    "    }\n"
    "}\n"
    "\n"
    "void keccak256(uchar* output, const uchar* input, uint input_len) {\n"
    "    ulong state[KECCAK_STATE_SIZE];\n"
    "    for (int i = 0; i < KECCAK_STATE_SIZE; i++) {\n"
    "        state[i] = 0;\n"
    "    }\n"
    "\n"
    "    uint offset = 0;\n"
    "    // Absorb only complete rate-sized blocks before permutation.\n"
    "    // For a 64-byte secp256k1 public key this loop is skipped; padding is\n"
    "    // applied to the same block. The previous implementation permuted once\n"
    "    // before padding and produced non-standard Keccak-256 digests.\n"
    "    while (input_len - offset >= KECCAK_RATE) {\n"
    "        for (uint i = 0; i < KECCAK_RATE; i++) {\n"
    "            ((uchar*)state)[i] ^= input[offset + i];\n"
    "        }\n"
    "        keccak_f(state);\n"
    "        offset += KECCAK_RATE;\n"
    "    }\n"
    "\n"
    "    uint remaining = input_len - offset;\n"
    "    for (uint i = 0; i < remaining; i++) {\n"
    "        ((uchar*)state)[i] ^= input[offset + i];\n"
    "    }\n"
    "    ((uchar*)state)[remaining] ^= 0x01;  // Keccak padding (not SHA3 0x06)\n"
    "    ((uchar*)state)[KECCAK_RATE - 1] ^= 0x80;\n"
    "    keccak_f(state);\n"
    "\n"
    "    for (int i = 0; i < 32; i++) {\n"
    "        output[i] = ((uchar*)state)[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// Test Kernel\n"
    "// ============================================================================\n"
    "\n"
    "__kernel void test_ecc_kernel_v2(\n"
    "    __global const uchar* private_key,\n"
    "    __global uchar* public_key,\n"
    "    __global uchar* address_out\n"
    ") {\n"
    "    (void)get_global_id(0);  // suppress unused warning\n"
    "    \n"
    "    uint256 prime;\n"
    "    prime.d[0] = 0xFFFFFFFEFFFFFC2FUL;\n"
    "    prime.d[1] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    prime.d[2] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    prime.d[3] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    \n"
    "    // Generate public key using STANDARD arithmetic\n"
    "    uchar local_priv[32];\n"
    "    for (int i = 0; i < 32; i++) {\n"
    "        local_priv[i] = private_key[i];\n"
    "    }\n"
    "    \n"
    "    uchar local_pub[64];\n"
    "    generate_public_key_std(local_pub, local_priv, &prime);\n"
    "    \n"
    "    // Copy to output\n"
    "    for (int i = 0; i < 64; i++) {\n"
    "        public_key[i] = local_pub[i];\n"
    "    }\n"
    "    \n"
    "    // Generate address\n"
    "    uchar hash[32];\n"
    "    keccak256(hash, local_pub, 64);\n"
    "    \n"
    "    // TRX address: 0x41 + last 20 bytes of hash\n"
    "    address_out[0] = 0x41;\n"
    "    for (int i = 0; i < 20; i++) {\n"
    "        address_out[i + 1] = hash[12 + i];\n"
    "    }\n"
    "}\n"
    "\n"
    "\n"
    "// ============================================================================\n"
    "// Focused field-operation debug kernel\n"
    "// Outputs 14 uint256 values (32 bytes each):\n"
    "// Gx2, Gy2, Y4, X_Y2, S, M, X3, Y3, Z3, Zi, Zi2, Zi3, Ax, Ay\n"
    "// ============================================================================\n"
    "__kernel void debug_field_ops_kernel(__global uchar* out) {\n"
    "    uint256 prime;\n"
    "    prime.d[0] = 0xFFFFFFFEFFFFFC2FUL;\n"
    "    prime.d[1] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    prime.d[2] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    prime.d[3] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "\n"
    "    uint256 gx, gy;\n"
    "    gx.d[0] = 0x59F2815B16F81798UL;\n"
    "    gx.d[1] = 0x029BFCDB2DCE28D9UL;\n"
    "    gx.d[2] = 0x55A06295CE870B07UL;\n"
    "    gx.d[3] = 0x79BE667EF9DCBBACUL;\n"
    "\n"
    "    gy.d[0] = 0x9C47D08FFB10D4B8UL;\n"
    "    gy.d[1] = 0xFD17B448A6855419UL;\n"
    "    gy.d[2] = 0x5DA4FBFC0E1108A8UL;\n"
    "    gy.d[3] = 0x483ADA7726A3C465UL;\n"
    "\n"
    "    uint256 gx2, gy2, y4, x_y2, S, M, X3, Y3, Z3;\n"
    "    uint256 temp1, temp2;\n"
    "\n"
    "    uint256_mul_mod(&gx2, &gx, &gx, &prime);\n"
    "    uint256_mul_mod(&gy2, &gy, &gy, &prime);\n"
    "    uint256_mul_mod(&y4, &gy2, &gy2, &prime);\n"
    "    uint256_mul_mod(&x_y2, &gx, &gy2, &prime);\n"
    "\n"
    "    uint256_add_mod(&S, &x_y2, &x_y2, &prime);\n"
    "    uint256_add_mod(&S, &S, &x_y2, &prime);\n"
    "    uint256_add_mod(&S, &S, &x_y2, &prime);\n"
    "\n"
    "    uint256_add_mod(&M, &gx2, &gx2, &prime);\n"
    "    uint256_add_mod(&M, &M, &gx2, &prime);\n"
    "\n"
    "    uint256_mul_mod(&temp1, &M, &M, &prime);\n"
    "    uint256_add_mod(&temp2, &S, &S, &prime);\n"
    "    uint256_sub_mod(&X3, &temp1, &temp2, &prime);\n"
    "\n"
    "    uint256_sub_mod(&temp1, &S, &X3, &prime);\n"
    "    uint256_mul_mod(&temp2, &M, &temp1, &prime);\n"
    "    uint256_add_mod(&temp1, &y4, &y4, &prime);\n"
    "    uint256_add_mod(&temp1, &temp1, &y4, &prime);\n"
    "    uint256_add_mod(&temp1, &temp1, &y4, &prime);\n"
    "    uint256_add_mod(&temp1, &temp1, &temp1, &prime);\n"
    "    uint256_sub_mod(&Y3, &temp2, &temp1, &prime);\n"
    "\n"
    "    uint256_add_mod(&Z3, &gy, &gy, &prime);\n"
    "\n"
    "    jacobian_point p2;\n"
    "    p2.x = X3;\n"
    "    p2.y = Y3;\n"
    "    p2.z = Z3;\n"
    "    uint256 Zi, Zi2, Zi3, Ax, Ay;\n"
    "    uint256 p_minus_2;\n"
    "    p_minus_2.d[0] = 0xFFFFFFFEFFFFFC2DUL;\n"
    "    p_minus_2.d[1] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    p_minus_2.d[2] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    p_minus_2.d[3] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    uint256 base = Z3;\n"
    "    uint256 exp = p_minus_2;\n"
    "    uint256 inv_acc = (uint256){{1, 0, 0, 0}};\n"
    "    while (!uint256_is_zero(&exp)) {\n"
    "        if (exp.d[0] & 1) {\n"
    "            uint256_mul_mod(&inv_acc, &inv_acc, &base, &prime);\n"
    "        }\n"
    "        uint256_mul_mod(&base, &base, &base, &prime);\n"
    "        uint256_rshift1(&exp, &exp);\n"
    "    }\n"
    "    Zi = inv_acc;\n"
    "    uint256_mul_mod(&Zi2, &Zi, &Zi, &prime);\n"
    "    uint256_mul_mod(&Zi3, &Zi2, &Zi, &prime);\n"
    "    uint256_mul_mod(&Ax, &X3, &Zi2, &prime);\n"
    "    uint256_mul_mod(&Ay, &Y3, &Zi3, &prime);\n"
    "\n"
    "    uint256 vals[14] = {gx2, gy2, y4, x_y2, S, M, X3, Y3, Z3, Zi, Zi2, Zi3, Ax, Ay};\n"
    "    for (int i = 0; i < 14; i++) {\n"
    "        uint256_to_global_bytes(out + i * 32, &vals[i]);\n"
    "    }\n"
    "}\n";
